version: '3'
services:
  mongodb:
    image: ftavares/rpi-mongo:3.0.9
    networks:
      viajes_network:
        aliases:
          - viajes_db
      mongodb_network:
        aliases:
          - viajes_db
    volumes:
      - mongodb_rpi_data:/data/db

  viajes-scrapper:
    build: .
    image: viajes:scrapper
    networks:
      viajes_network:
        aliases:
          - viajes_scrapper

volumes:
  mongodb_rpi_data:

networks:
  viajes_network:
    driver: bridge
  mongodb_network:
    driver: bridge